version: "3.8"

networks:
  pleasanter-service-network:

services:
  postgres-db:
    build: postgres/.
    container_name: db-container
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGPASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DB_EXTENSION=pg_trgm
      - TZ=${TZ}
      - PGTZ=${TZ}
    command: 'postgres -c config_file="/etc/postgresql.conf"'
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/conf/postgresql.conf:/etc/postgresql.conf
      - ./db-data:/var/lib/postgresql/data
      - ./db-arclog:/var/lib/postgresql/arclog
    networks:
      - pleasanter-service-network
    env_file:
      - .env
    restart: always
  pleasanter-web:
    build:
      context: pleasanter/.
      args:
        - GIT_HASH=${GIT_HASH}
    networks:
      - pleasanter-service-network
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    restart: always
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - ${WEB_IP}:80:80
      - ${WEB_IP}:443:443
    environment:
      DOMAINS: >-
              ${WEB_IP} -> http://pleasanter-web
      CLIENT_MAX_BODY_SIZE: 500M
      #HSTS_MAX_AGE: 60
      #ERROR_LOG: stdout
      #ACCESS_LOG: stderr
      STAGE: 'local'
      TZ: ${TZ}
    networks:
      - pleasanter-service-network
    volumes:
      - ./ssl_data:/var/lib/https-portal
    env_file:
      - .env
    restart: always
    depends_on:
      - pleasanter-web
      - postgres-db
